### ISSUE TITLE
Recipe recipes-iot/aws-iot-fleetwise won't work with custom provisioningTemplates

### ISSUE THREAD

**Issue by garciap2g** [aws4embeddedlinux/meta-aws#4133]
The Provisioning Template name has been hardcoded on https://github.com/aws4embeddedlinux/meta-aws/blob/master/recipes-iot/aws-iot-greengrass/files/config.yaml.template

```
aws.greengrass.FleetProvisioningByClaim:
    configuration:
      rootPath: "/greengrass/v2"
      awsRegion: "${AWS_DEFAULT_REGION}"
      iotDataEndpoint: "${IOT_DATA_ENDPOINT}"
      iotCredentialEndpoint: "${IOT_CRED_ENDPOINT}"
      iotRoleAlias: "${TE_ROLE_ALIAS}"
      provisioningTemplate: "GreengrassFleetProvisioningTemplate"
```

Recipe will not work in environments where the template name is different from "GreengrassFleetProvisioningTemplate".
